name: "Build and Push Images"
env:
  DOCKER_COMPOSE_VERSION: 1.23.0

on:
  push:
    branches:
      - main
      - release-*

jobs:
  BUILD_AND_PUSH_IMAGES:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.5
        id: go

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: 20.10
          docker_channel: stable

      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: src/github.com/goharbor/harbor

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Images
        run: |
          set -x
          cd src/github.com/goharbor/harbor
          
          target_branch="$(echo ${GITHUB_REF#refs/heads/})"
          target_release_version=$(cat ./VERSION)

          if [[ $target_branch == "release-"* ]]; then
            Harbor_Build_Base_Tag=$target_release_version
            Harbor_Assets_Version=$target_release_version
          else
            Harbor_Build_Base_Tag=dev
            Harbor_Assets_Version=$target_release_version-'build.'$GITHUB_RUN_NUMBER
          fi

          # Build base images first if needed
          make "VERSIONTAG=${Harbor_Assets_Version}" "BASEIMAGETAG=${Harbor_Build_Base_Tag}" "PUSHBASEIMAGE=true" "PULL_BASE_FROM_DOCKERHUB=true" build

          # Build and push harbor images
          make "VERSIONTAG=${Harbor_Assets_Version}" "BASEIMAGETAG=${Harbor_Build_Base_Tag}" "PUSHIMAGE=true" push