name: build harbor image

on:
  push:
    # branches:
    #   - 'main'

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - trivy-adapter
          # - core
          # - db
          # - exporter
          # - jobservice
          # - log
          # - nginx
          # - portal
          # - prepare
          # - redis
          # - registry
          # - registryctl

    defaults:
      run:
        shell: bash
        working-directory: ./harbor

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
         
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: debug
        run: |
          set -x
          ls -ahl
          echo $SHELL
          pwd